// frontend/src/components/help/llmProviders.js
//
// Common LLM endpoint URLs surfaced in the Settings → LLM help drawer.
// Adding a provider: append a row. Removing: drop the row. No backend
// round-trip; this is intentionally a static const so it's trivial to
// maintain and ships in the bundle without a fetch.

export const LLM_PROVIDERS = [
  { name: 'OpenAI',
    base_url: 'https://api.openai.com/v1',
    api_type: 'openai',
    signup_url: 'https://platform.openai.com/api-keys',
    signup_label: 'platform.openai.com' },
  { name: 'Anthropic',
    base_url: 'https://api.anthropic.com/v1',
    api_type: 'anthropic',
    signup_url: 'https://console.anthropic.com/settings/keys',
    signup_label: 'console.anthropic.com' },
  { name: 'Google Gemini',
    base_url: 'https://generativelanguage.googleapis.com/v1beta/openai/',
    api_type: 'openai',
    signup_url: 'https://aistudio.google.com/apikey',
    signup_label: 'aistudio.google.com' },
  { name: 'OpenRouter',
    base_url: 'https://openrouter.ai/api/v1',
    api_type: 'openai',
    signup_url: 'https://openrouter.ai/keys',
    signup_label: 'openrouter.ai/keys' },
  { name: 'Abacus.ai (RouteLLM)',
    base_url: 'https://routellm.abacus.ai/v1',
    api_type: 'openai',
    signup_url: 'https://abacus.ai/app/apikeys',
    signup_label: 'abacus.ai' },
  { name: 'Groq',
    base_url: 'https://api.groq.com/openai/v1',
    api_type: 'openai',
    signup_url: 'https://console.groq.com/keys',
    signup_label: 'console.groq.com' },
  { name: 'Together AI',
    base_url: 'https://api.together.xyz/v1',
    api_type: 'openai',
    signup_url: 'https://api.together.xyz/settings/api-keys',
    signup_label: 'api.together.xyz' },
  { name: 'Fireworks',
    base_url: 'https://api.fireworks.ai/inference/v1',
    api_type: 'openai',
    signup_url: 'https://fireworks.ai/api-keys',
    signup_label: 'fireworks.ai' },
  { name: 'DeepInfra',
    base_url: 'https://api.deepinfra.com/v1/openai',
    api_type: 'openai',
    signup_url: 'https://deepinfra.com/dash/api_keys',
    signup_label: 'deepinfra.com' },
  { name: 'xAI Grok',
    base_url: 'https://api.x.ai/v1',
    api_type: 'openai',
    signup_url: 'https://console.x.ai',
    signup_label: 'console.x.ai' },
  { name: 'Mistral',
    base_url: 'https://api.mistral.ai/v1',
    api_type: 'openai',
    signup_url: 'https://console.mistral.ai/api-keys/',
    signup_label: 'console.mistral.ai' },
  { name: 'Ollama (local)',
    base_url: 'http://localhost:11434/v1',
    api_type: 'ollama',
    signup_url: 'https://ollama.com',
    signup_label: 'ollama.com',
    signup_note: 'No key — install locally' },
  { name: 'LM Studio (local)',
    base_url: 'http://localhost:1234/v1',
    api_type: 'openai',
    signup_url: 'https://lmstudio.ai',
    signup_label: 'lmstudio.ai',
    signup_note: 'No key — install locally' },
]

/** Slugify a provider name into an endpoint-name suggestion. */
export function providerNameToSlug(name) {
  return (name || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
}
