"""artifact sink — saves output as a markdown artifact in the project.

Default sink for scheduled_jobs. Auto-embeds via the standard pipeline.
"""
from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from typing import Any

from jobs.sinks import register

logger = logging.getLogger(__name__)


def _slug(s: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "-", (s or "").strip().lower()).strip("-")
    return s[:60] or "report"


@register("artifact", description="Save run output as a markdown artifact.")
async def to_artifact(ctx, content: str, opts: dict) -> dict[str, Any]:
    from artifacts.store import get_store, project_slug
    from artifacts import embedder

    proj = project_slug(ctx.project_id)
    title = opts.get("title") or ctx.title or "Scheduled run"
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    template = opts.get("artifact_path") or f"{proj}/reports/{{date}}/{{title}}.md"
    path = (template
            .replace("{date}", today)
            .replace("{title}", _slug(title))
            .replace("{project}", proj))

    body = (
        f"# {title}\n\n"
        f"_Generated by job `{ctx.job_id[:8]}` at {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_\n\n"
        f"{content}"
    )

    a = get_store().create(
        project_id=ctx.project_id,
        path=path,
        content=body,
        content_type="text/markdown",
        title=title,
        tags=["scheduled-run"] + list(opts.get("tags") or []),
        source={"kind": "scheduled_job", "job_id": ctx.job_id, "schedule_id": opts.get("schedule_id")},
        edited_by=f"job:{ctx.job_id[:8]}",
    )
    embedder.schedule_embed(a["id"], ctx.project_id, immediate=True)
    return {"sink": "artifact", "artifact_id": a["id"], "path": a["path"]}
