"""Generate docs/tools.md from the agent's tool schemas.

Run from the repo root after adding or changing a tool:
    ./.venv/bin/python scripts/gen_tools_doc.py

A test (tests/integration/test_prompt_budget.py) fails when docs/tools.md
is out of date.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "tools.md"


def _first_sentence(text: str) -> str:
    text = " ".join((text or "").split())
    m = re.search(r"(?<!e\.g)(?<!i\.e)(?<!etc)\.\s", text)
    if m and m.start() < 240:
        return text[: m.start() + 1]
    return text if len(text) <= 240 else text[:237].rstrip() + "…"


def render() -> str:
    sys.path.insert(0, str(ROOT / "backend"))
    from agent.tools import HOST_EXEC_TOOLS, TOOL_SCHEMAS
    try:
        from agent.browser_tools import BROWSER_TOOL_SCHEMAS
    except Exception:
        BROWSER_TOOL_SCHEMAS = []

    def rows(schemas):
        out = []
        for t in sorted(schemas, key=lambda t: t["function"]["name"]):
            fn = t["function"]
            props = fn.get("parameters", {}).get("properties", {}) or {}
            required = set(fn.get("parameters", {}).get("required", []) or [])
            params = ", ".join(f"`{p}`" + ("" if p in required else "?") for p in props) or "—"
            note = " *(host exec)*" if fn["name"] in HOST_EXEC_TOOLS else ""
            desc = _first_sentence(fn.get("description", "")).replace("|", "\\|")
            out.append(f"| `{fn['name']}`{note} | {desc} | {params} |")
        return out

    lines = [
        "# Agent tools",
        "",
        "<!-- Generated by scripts/gen_tools_doc.py from agent/tools.py — do not edit by hand. -->",
        "",
        f"{len(TOOL_SCHEMAS)} built-in tools (schemas and dispatch in `backend/agent/tools.py`). "
        "MCP servers add their own tools at runtime as `mcp_<server>_<tool>`. "
        "`?` marks an optional parameter. *(host exec)* tools are only offered where "
        "`AGENT_HOST_EXEC` allows them (interactive chat and coding tasks by default).",
        "",
        "| Tool | What it does | Parameters |",
        "| --- | --- | --- |",
        *rows(TOOL_SCHEMAS),
    ]
    if BROWSER_TOOL_SCHEMAS:
        lines += [
            "",
            "## Browser tools",
            "",
            "Offered only when Playwright browser tools are enabled (`agent/browser_tools.py`).",
            "",
            "| Tool | What it does | Parameters |",
            "| --- | --- | --- |",
            *rows(BROWSER_TOOL_SCHEMAS),
        ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    OUT.write_text(render())
    print(f"wrote {OUT.relative_to(ROOT)}")
